project_id = "cectqtufttubsepyiolr"

[functions.close-store-attendance]
verify_jwt = false

[functions.send-incidence-email]
verify_jwt = true

[functions.remove-absence]
verify_jwt = true

[functions.self-attendance-status]
verify_jwt = false

[functions.mark-store-lunch]
verify_jwt = true

[functions.mark-store-exit]
verify_jwt = true

[functions.server-clock]
verify_jwt = false
